import { Control } from "./Control";
import "./globals.css";
import Link from "next/link";

// metadata 는 서버 컴포넌트에서만 작동
export const metadata = {
  title: "STO PROJECT",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // 서버 경로를 넣어서, 서버에서 데이터를 가져오기(fetching)
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', {
    // next: { revalidate: 10 },  // 10초 간만 cache 유지, 10초 이후 fresh data 가져오고 다시 cache 저장
    // next: { revalidate: 0 },   // 캐쉬를 쓰지 않겠다.
    cache: "no-store", // 캐쉬를 쓰지 않겠다.
  });

  const topics = await res.json();

  return (
    <html>
      <body>
        <h1>
          {" "}
          <Link href="/"> home 으로 이동 </Link>{" "}
        </h1>

        <ol>
          {/* <li> <a href='/read/1' > html 상세 로 이동 </a>   </li> */}
          {/* <li>
              {" "}
              <Link href="/read/1"> html 상세 로 이동 </Link>{" "}
            </li>
            <li>
              {" "}
              <Link href="/read/2"> css 상세 로 이동</Link>{" "}
            </li> */}

          {/* 동적으로 Link 생성하기 */}
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                {" "}
                <Link href={`/read/${topic.id}`}> {topic.title} </Link>{" "}
              </li>
            );
          })}
        </ol>  

        <Control />

        <br></br>
        <br></br>
        <br></br>

          <Link href = {"/admin/main"} > 🚀🚀🚀 어드민 페이지 이동 </Link>

        {/* page.js 에서 적혀진게, children 을 타고 옴 | 다만, 어디서 오는건지는 불명확 😥   */}
        {children}

        
      </body>
    </html>
  );
}
