"use client";

import "./globals.css";
import Link from "next/link";
import { useEffect, useState } from "react";


// // metadata 는 서버 컴포넌트에서만 작동 
//   export const metadata = {
//     title: "STO PROJECT",
//     description: "Generated by create next app",
//   };

export default function RootLayout({ children }) {
  const [topics, setTopics] = useState([]);

  useEffect(() => {
    // 서버 경로를 넣어서, 서버에서 데이터를 가져오기(fetching)
    fetch("http://localhost:9999/topics") 
      .then((resp) => resp.json()) // 받아온 데이터를 'json' 형식으로 변환
      .then((result) => {
        setTopics(result);
      });
  });

  return (
    <html>
      <body>
        <h1>
          {" "}
          <Link href="/"> [layout 에서 작성] home 으로 이동 </Link>{" "}
        </h1>

        <ol>
            {/* <li> <a href='/read/1' > html 상세 로 이동 </a>   </li> */}
            {/* <li>
              {" "}
              <Link href="/read/1"> html 상세 로 이동 </Link>{" "}
            </li>
            <li>
              {" "}
              <Link href="/read/2"> css 상세 로 이동</Link>{" "}
            </li> */}

          {/* 동적으로 Link 생성하기 */}
          {topics.map( (topic) => {
            return <li key={topic.id}> <Link href={`/read/${topic.id}`} >  {topic.title}  </Link> </li>
          } )

          }


        </ol>

        <ul>
          <li>
            {" "}
            <Link href="/create"> Create </Link>{" "}
          </li>
          <li>
            {" "}
            <Link href="/update"> Update </Link>{" "}
          </li>
          <li>
            {" "}
            <input type="button" value="delete" />{" "}
          </li>
        </ul>

        {/* page.js 에서 적혀진게, children 을 타고 옴 | 다만, 어디서 오는건지는 불명확 😥   */}
        {children}
      </body>
    </html>
  );
}
