import "./globals.css";
import type { Metadata } from "next";

import Link from "next/link";


export const metadata: Metadata = {
  title: "🐣STO PROJECT🐣",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        

        {/* page 내용들 */}
        {children}
      

      </body>
    </html>
  );
}
